name: localstorage
description: Simple json file-based storage for flutter. Alternative to react-native AsyncStorage
version: 4.1.0
homepage: https://github.com/lesnitsky/flutter_localstorage

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
